

<div class="index-nav-top">
	<div class="index-nav">
		<div class="index-nav-img">
			<img src="<?php echo $this->getSkinUrl('supplier/images/h-1.png'); ?>"/>
		</div>
		<div class="index-nav-txt">Product</div>
	</div>

	<div class="index-nav">
		<div class="index-nav-img">
			<img src="<?php echo $this->getSkinUrl('supplier/images/h-2.png'); ?>"/>
		</div>
		<div class="index-nav-txt">Logistic</div>
	</div>
	<div class="index-nav">
		<div class="index-nav-img">
			<img src="<?php echo $this->getSkinUrl('supplier/images/h-3.png'); ?>"/>
		</div>
		<div class="index-nav-txt">Orders</div>
	</div>
	<div class="index-nav">
		<div class="index-nav-img">
			<img src="<?php echo $this->getSkinUrl('supplier/images/h-4.png'); ?>"/>
		</div>
		<div class="index-nav-txt">Payment</div>
	</div>
	<div class="index-nav">
		<div class="index-nav-img">
			<img src="<?php echo $this->getSkinUrl('supplier/images/h-5.png'); ?>"/>
		</div>
		<div class="index-nav-txt">Report</div>
	</div>



</div>

<div class="clear"></div>