<!-- 轮播 -->
	<!-- <div id="home_banner" class="carousel slide" style="margin: 0;">
		轮播（Carousel）项目	
		<div class="carousel-inner">
			<div class="item active" >
				<img src="<?php echo $this->getSkinUrl("images/banner_01.jpg");?>" class="banner_img" alt="First slide">
			</div>
			<div class="item">
				<img src="<?php echo $this->getSkinUrl("images/banner_02.jpg");?>" class="banner_img" alt="Second slide">
			</div>
			<div class="item">
				<img src="<?php echo $this->getSkinUrl("images/banner_03.jpg");?>" class="banner_img" alt="Third slide">
			</div>
		</div>
	</div> -->