<!-- 导航 -->
	<div class="header-bottom">
		<div class="fixed-header">
			<div class="my_container">
				<div class="logo">
					<a href="index.html">
						<img src="images/design_logo.png" width="100px" height="53px">
					</a>
				</div>
				<div class="left_menu">
					<ul>
						<li>
							<a href="#" class="active">
								HOME
							</a>
						</li>
						<li>
							<a href="#"> 
								SEASONS
							</a>
						</li>
						<li>
							<a href="#">
								ABOUT US
							</a>
						</li>
						<li>
							<a href="#">
								OUR PROCESS
							</a>
						</li>
						<li>
							<a href="#">
								FROM THE MEDIA
							</a>
						</li>
						<li>
							<a href="#">
								CONTACT US
							</a>
						</li>
					</ul>
				</div>
				<div class="right_menu">
					<ul>
						<li>
							<a href="#">
								REGISTER
							</a>
						</li>
						<li>
							<a href="#">
								LOGIN
							</a>
						</li>
						<li>
							<a href="#">
								MY CART(0)
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<hr style="clear:left;">
	</div>